services:
  app:
    build: .
    container_name: quanlycongvan_app
    ports:
      - "8000:8080"
      - "8001:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=DocumentManagement;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${PFX_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - C:/Users/phamh/.aspnet/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: quanlycongvan_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  mssql-data:
  grafana-data: