global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'document_management_app'
    scheme: https
    
    tls_config:
      insecure_skip_verify: true
      
    static_configs:
      - targets: ['app:8081']